### ISSUE TITLE
bilibili直播规则改变，请问作者有时间适配嘛

### ISSUE THREAD

**Issue by TianLuoQin** [ClydeTime/BiliBili#2]
<img width="768" alt="image" src="https://github.com/user-attachments/assets/d34714c4-5dac-4d71-afc4-96283a127dcf">
现在需要做每日任务才能维持粉丝勋章，三天不做自动熄灭只能付费点亮。不知道大佬有没有时间做一下适配？

**Comment by ClydeTime** [comment]
太复杂，暂不考虑。脚本本身就不关注直播内容，算是添头，找找专业做这方面的
